name: CI

on:
  pull_request:
    branches:
      - master
      - bindgen
  push:
    branches:
      - master
      - bindgen

env:
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        thing:
        - x86_64-msvc
        include:
        - thing: x86_64-msvc
          target: x86_64-pc-windows-msvc
          rust: stable-x86_64-pc-windows-msvc
          os: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install Rust (rustup)
      run: rustup update ${{ matrix.rust }} --no-self-update && rustup default ${{ matrix.rust }}
      shell: bash
    - run: rustup target add ${{ matrix.target }}
    - name: Install nasm
      if: startsWith(matrix.os, 'windows')
      run: choco install nasm
      shell: cmd
    - if: startsWith(matrix.os, 'windows')
      # CI's Windows doesn't have require root certs
      run: cargo test --workspace --exclude tokio-boring --exclude hyper-boring
      name: Run tests (Windows)
    - if: "!startsWith(matrix.os, 'windows')"
      run: cargo test
      name: Run tests (not Windows)
